version: '2'
services:
  ui-live:
    image: node:8
    depends_on:
    - api
    user: "node"
    working_dir: /home/node/app
    volumes:
    - ./src:/home/node/app
    restart: always
    command: npm run dev
    ports:
      - 8081:2000
    environment:
      HOST: 0.0.0.0
      PORT: 2000
      PUBLIC: localhost:8081
      API_URL: localhost:8082
  ui-build:
    image: localhost/open-cura/ui:local-0.1
    ports:
      - 8080:80
    restart: always
    depends_on:
      - api
  api:
    image: localhost/open-cura/api:0.4
    ports:
      - 8082:80
    restart: always
    depends_on:
      - api-sql
    #FIXME these are probably not used? as .env file is used? FIXME
    environment:
      - APP_NAME=WikWiki-api
      - APP_ENV=local
      - APP_KEY=sod9i29001ftqammznxb810ejd8s098d
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - APP_TIMEZONE=UTC
      - LOG_CHANNEL=stack
      - LOG_SLACK_WEBHOOK_URL=
      - DB_CONNECTION=mysql
      - DB_HOST=api-sql
      - DB_PORT=3306
      - DB_DATABASE=apidb
      - DB_USERNAME=apiuser
      - DB_PASSWORD=apiuser-pass
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - JWT_SECRET=J0sa909asfj29k0219r9k01r109rrq
  api-sql:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: imarootpassword
    restart: always
    volumes:
    # TODO could just mount the whole dir? but should check that no other files are there first....
    - ./docker-compose/api-sql/docker-entrypoint-initdb.d/01_createUsers.sql:/docker-entrypoint-initdb.d/01_createUsers.sql
    - ./docker-compose/api-sql/docker-entrypoint-initdb.d/02_seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
